#! /usr/bin/env ruby

require 'pg'

# Need an object
CONNECTION = PG.connect(dbname: database_name)

# commands
def display_help()
  help_text = <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
    HELP
  puts help_text
end

def list_expenses()
  result = CONNECTION.exec('SELECT * FROM expenses;')

  result.each do |row|
    columns = [
      row['id'].rjust(3),
      row['created_on'].rjust(26),
      row['amount'].rjust(8),
      row['memo'],
    ]
    puts columns.join(' | ')
  end
end

def add_expense(amount, memo)
  sql =
    "INSERT INTO expenses (amount, memo) VALUES (#{amount}, '#{memo.gsub(/\'/, "''")}')"
  CONNECTION.exec(sql)
end

# reading args from command line
args = ARGV

if args.empty?
  display_help
else
  command = args[0]
  list_expenses if command == 'list'
  if command == 'add'
    abort 'You must provide an amount and memo.' unless (args[1] && args[2])
    add_expense(args[1], args[2])
  end
end
